### ISSUE TITLE
Pong Game not working from Kivy main website

### ISSUE THREAD

**Issue by NickC151** [phoboslab/high_impact#4]
Hi Everyone, I am learning Kivy and tried runing some lines of code from Kivy main page under tutorials Pong Game. 

--> https://kivy.org/doc/stable/tutorials/pong.html

At the end of the page you will find the entire .py and .kv code.
And it just doesn't work. 
I am curious to know why and see the code runing.

**Comment by phoboslab** [comment]
You are definitely the wrong repository; high_impact has _nothing_ to do with Kivy. It seems like you want to open your issue here: https://github.com/kivy

Also, you problem description is not helpful. "Doesn't work" is not telling us anything. Does your computer explode? You get a bluescreen? An error message? Which one? Ask better questions and you'll get better answers.
